[CODE] 0
[INFO] exec() has been disabled for security reasons
[FILE] think\exception\ErrorException in vendor/zoujingli/think-library/src/service/ProcessService.php line 140
[TIME] 2023-04-06 11:08:02

[TRACE]
#0 [internal function]: think\initializer\Error->appError()
#1 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/zoujingli/think-library/src/service/ProcessService.php(140): exec()
#2 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/zoujingli/think-library/src/service/ProcessService.php(163): think\admin\service\ProcessService::exec()
#3 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/zoujingli/think-library/src/service/ProcessService.php(49): think\admin\service\ProcessService::isfile()
#4 /www/wwwroot/uexwash.com/ThinkAdmin/app/admin/controller/Queue.php(49): think\admin\service\ProcessService::think()
#5 [internal function]: app\admin\controller\Queue->app\admin\controller\{closure}()
#6 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/zoujingli/think-library/src/helper/QueryHelper.php(284): call_user_func()
#7 /www/wwwroot/uexwash.com/ThinkAdmin/app/admin/controller/Queue.php(57): think\admin\helper\QueryHelper->layTable()
#8 [internal function]: app\admin\controller\Queue->index()
#9 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/topthink/framework/src/think/Container.php(344): ReflectionMethod->invokeArgs()
#10 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/topthink/framework/src/think/route/dispatch/Controller.php(110): think\Container->invokeReflectMethod()
#11 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/topthink/framework/src/think/Pipeline.php(59): think\route\dispatch\Controller->think\route\dispatch\{closure}()
#12 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/topthink/framework/src/think/Pipeline.php(66): think\Pipeline->think\{closure}()
#13 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/topthink/framework/src/think/route/dispatch/Controller.php(113): think\Pipeline->then()
#14 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/topthink/framework/src/think/route/Dispatch.php(90): think\route\dispatch\Controller->exec()
#15 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/topthink/framework/src/think/Route.php(785): think\route\Dispatch->run()
#16 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/topthink/framework/src/think/Pipeline.php(59): think\Route->think\{closure}()
#17 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/zoujingli/think-library/src/Library.php(150): think\Pipeline->think\{closure}()
#18 [internal function]: think\admin\Library->think\admin\{closure}()
#19 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/topthink/framework/src/think/Middleware.php(142): call_user_func()
#20 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/topthink/framework/src/think/Pipeline.php(85): think\Middleware->think\{closure}()
#21 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/topthink/framework/src/think/Pipeline.php(66): think\Pipeline->think\{closure}()
#22 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/topthink/framework/src/think/Route.php(786): think\Pipeline->then()
#23 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/topthink/framework/src/think/Http.php(216): think\Route->dispatch()
#24 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/topthink/framework/src/think/Http.php(206): think\Http->dispatchToRoute()
#25 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/topthink/framework/src/think/Pipeline.php(59): think\Http->think\{closure}()
#26 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/zoujingli/think-library/src/support/middleware/Multiple.php(79): think\Pipeline->think\{closure}()
#27 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/topthink/framework/src/think/Pipeline.php(59): think\admin\support\middleware\Multiple->think\admin\support\middleware\{closure}()
#28 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/topthink/framework/src/think/Pipeline.php(66): think\Pipeline->think\{closure}()
#29 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/zoujingli/think-library/src/support/middleware/Multiple.php(80): think\Pipeline->then()
#30 [internal function]: think\admin\support\middleware\Multiple->handle()
#31 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/topthink/framework/src/think/Middleware.php(142): call_user_func()
#32 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/topthink/framework/src/think/Pipeline.php(85): think\Middleware->think\{closure}()
#33 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/topthink/framework/src/think/middleware/LoadLangPack.php(57): think\Pipeline->think\{closure}()
#34 [internal function]: think\middleware\LoadLangPack->handle()
#35 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/topthink/framework/src/think/Middleware.php(142): call_user_func()
#36 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/topthink/framework/src/think/Pipeline.php(85): think\Middleware->think\{closure}()
#37 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/zoujingli/think-library/src/support/middleware/JwtInit.php(123): think\Pipeline->think\{closure}()
#38 [internal function]: think\admin\support\middleware\JwtInit->handle()
#39 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/topthink/framework/src/think/Middleware.php(142): call_user_func()
#40 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/topthink/framework/src/think/Pipeline.php(85): think\Middleware->think\{closure}()
#41 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/topthink/framework/src/think/Pipeline.php(66): think\Pipeline->think\{closure}()
#42 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/topthink/framework/src/think/Http.php(207): think\Pipeline->then()
#43 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/topthink/framework/src/think/Http.php(170): think\Http->runWithRequest()
#44 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/zoujingli/think-library/src/service/RuntimeService.php(213): think\Http->run()
#45 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/zoujingli/think-library/src/service/SystemService.php(407): think\admin\service\RuntimeService::doWebsiteInit()
#46 /www/wwwroot/uexwash.com/ThinkAdmin/vendor/zoujingli/think-library/src/service/SystemService.php(382): think\admin\service\SystemService::__callStatic()
#47 /www/wwwroot/uexwash.com/ThinkAdmin/public/index.php(25): think\admin\service\SystemService->__call()
#48 {main}