<?php /*a:3:{s:73:"/www/wwwroot/test.cloudskys.cn/ThinkAdmin/app/store/view/store/index.html";i:1675757248;s:83:"/www/wwwroot/test.cloudskys.cn/ThinkAdmin/app/store/view/../../admin/view/main.html";i:1670552399;s:80:"/www/wwwroot/test.cloudskys.cn/ThinkAdmin/app/store/view/store/index_search.html";i:1675755045;}*/ ?>
<div class="layui-card"><?php if(!(empty($title) || (($title instanceof \think\Collection || $title instanceof \think\Paginator ) && $title->isEmpty()))): ?><div class="layui-card-header"><span class="layui-icon font-s10 color-desc margin-right-5">&#xe65b;</span><?php echo htmlentities((isset($title) && ($title !== '')?$title:''),ENT_QUOTES); ?><div class="pull-right"><!--<?php if(auth("add")): ?>--><button class='layui-btn layui-btn-sm layui-btn-primary' data-open='<?php echo url("add"); ?>'>添加门店</button><!--<?php endif; ?>--></div></div><?php endif; ?><div class="layui-card-line"></div><div class="layui-card-body"><div class="layui-card-html"><div class="think-box-shadow"><fieldset><legend>条件搜索</legend><form class="layui-form layui-form-pane form-search" action="<?php echo sysuri(); ?>" onsubmit="return false" method="get" autocomplete="off"><div class="layui-form-item layui-inline"><label class="layui-form-label">门店名称</label><label class="layui-input-inline"><input name="name" value="<?php echo htmlentities((isset($get['name']) && ($get['name'] !== '')?$get['name']:''),ENT_QUOTES); ?>" placeholder="请输入门店名称" class="layui-input"></label></div><div class="layui-form-item layui-inline"><label class="layui-form-label">状态</label><div class="layui-input-inline"><select name='status' lay-search class="layui-select"><option value=''>-- 全部 --</option><?php foreach(['禁用','可用️'] as $key=>$value): if($key == input('get.status')): ?><option selected value="<?php echo htmlentities($key,ENT_QUOTES); ?>"><?php echo htmlentities($value,ENT_QUOTES); ?></option><?php else: ?><option value="<?php echo htmlentities($key,ENT_QUOTES); ?>"><?php echo htmlentities($value,ENT_QUOTES); ?></option><?php endif; ?><?php endforeach; ?></select></div></div><div class="layui-form-item layui-inline"><button class="layui-btn layui-btn-primary"><i class="layui-icon">&#xe615;</i> 搜 索</button></div></form></fieldset><script></script><table id="StoreTable" data-url="<?php echo sysuri(); ?>" data-target-search="form.form-search"></table></div></div></div><script>
    $(function () {
        $('#StoreTable').layTable({
            even: true, height: 'full',
            sort: {field: 'id', type: 'desc'},
            cols: [[
                {checkbox: true},
                {field: 'id', title: 'ID', width: 80, sort: true, align: 'center'},
                {field: 'name', title: '门店名', minWidth: 20, sort: true, align: 'center'},
                {field: 'cover', title: '封面图', minWidth: 20, sort: true, align: 'center',templet: '#coverTpl'},
                {field: 'address', title: '地址', minWidth: 30},
                {field: 'work_time', title: '工作时间', minWidth: 30},
                {field: 'id', title: '业绩', minWidth: 150},
                {toolbar: '#toolbar', title: '操作面板', align: 'center', minWidth: 150, fixed: 'right'}
            ]]
        });
    });
</script><script type="text/html" id="coverTpl"><div class="headimg headimg-no" data-tips-hover data-tips-image data-lazy-src="{{d.cover}}"></div></script><script type="text/html" id="toolbar"><!--<?php if(auth('remove')): ?>--><a data-action='<?php echo url("remove"); ?>' data-value="id#{{d.id}}" data-confirm="确认要删除这条记录吗？" class="layui-btn layui-btn-sm layui-btn-danger">删 除</a><!--<?php endif; ?>--><!--<?php if(auth("edit")): ?>--><a class="layui-btn layui-btn-sm"  data-open='<?php echo url("edit"); ?>?id={{d.id}}'>编 辑</a><!--<?php endif; ?>--></script></div>