<?php /*a:1:{s:65:"/www/wwwroot/uexwash.com/ThinkAdmin/app/admin/view/base/form.html";i:1670552399;}*/ ?>
<form action="<?php echo sysuri(); ?>" method="post" data-auto="true" class="layui-form layui-card" data-table-id="BaseTable"><div class="layui-card-body padding-left-40"><div class="layui-form-item label-required-prev"><div class="help-label"><b>数据类型</b>DataType</div><?php if(isset($vo['type'])): ?><label><input readonly value="<?php echo htmlentities((isset($vo['type']) && ($vo['type'] !== '')?$vo['type']:''),ENT_QUOTES); ?>" class="layui-input think-bg-gray"></label><?php else: ?><select class="layui-select" lay-filter="DataType"><?php foreach($types as $type): if((isset($vo['type']) and $type == $vo['type']) or ($type == input('get.type'))): ?><option selected value="<?php echo htmlentities($type,ENT_QUOTES); ?>"><?php echo htmlentities($type,ENT_QUOTES); ?></option><?php else: ?><option value="<?php echo htmlentities($type,ENT_QUOTES); ?>"><?php echo htmlentities($type,ENT_QUOTES); ?></option><?php endif; ?><?php endforeach; ?></select><script>
                (function (callable) {
                    layui.form.on('select(DataType)', callable);
                    callable({value: "<?php echo htmlentities((isset($vo['type']) && ($vo['type'] !== '')?$vo['type']:''),ENT_QUOTES); ?>" || $('[lay-filter=DataType]').val()});
                })(function (data) {
                    if (data.value === '--- 新增类型 ---') {
                        $('#DataTypeInput').removeClass('layui-hide').find('input').val('').focus();
                    } else {
                        $('#DataTypeInput').addClass('layui-hide').find('input').val(data.value);
                    }
                });
            </script><?php endif; ?><p class="help-block">请选择数据类型，数据创建后不能再次修改哦 ~</p><div id="DataTypeInput" class="layui-hide relative"><input class="layui-input" maxlength="20" name="type" required placeholder="请输入数据类型" value="<?php echo htmlentities((isset($vo['type']) && ($vo['type'] !== '')?$vo['type']:''),ENT_QUOTES); ?>"><p class="help-block">请输入新的数据类型，数据创建后不能再次修改哦 ~</p></div></div><label class="layui-form-item relative block"><span class="help-label"><b>数据编码</b>DataCode</span><?php if(isset($vo['code'])): ?><input readonly maxlength="100" class="layui-input think-bg-gray" name="code" value='<?php echo htmlentities((isset($vo['code']) && ($vo['code'] !== '')?$vo['code']:""),ENT_QUOTES); ?>' required placeholder="请输入数据编码"><?php else: ?><input maxlength="100" class="layui-input" name="code" value='<?php echo htmlentities((isset($vo['code']) && ($vo['code'] !== '')?$vo['code']:""),ENT_QUOTES); ?>' required placeholder="请输入数据编码"><?php endif; ?><span class="help-block">请输入新的数据编码，数据创建后不能再次修改，同种数据类型的数据编码不能出现重复 ~</span></label><label class="layui-form-item relative block"><span class="help-label"><b>数据名称</b>DataName</span><input maxlength="500" class="layui-input" name="name" value='<?php echo htmlentities((isset($vo['name']) && ($vo['name'] !== '')?$vo['name']:""),ENT_QUOTES); ?>' required placeholder="请输入数据名称"><span class="help-block">请输入当前数据名称，请尽量保持名称的唯一性，数据名称尽量不要出现重复 ~</span></label><label class="layui-form-item relative block"><span class="help-label"><b>数据内容</b>DataContent</span><textarea name="content" class="layui-textarea" placeholder="请输入数据内容"><?php echo htmlentities((isset($vo['content']) && ($vo['content'] !== '')?$vo['content']:''),ENT_QUOTES); ?></textarea></label></div><div class="hr-line-dashed"></div><?php if(!(empty($vo['id']) || (($vo['id'] instanceof \think\Collection || $vo['id'] instanceof \think\Paginator ) && $vo['id']->isEmpty()))): ?><input type='hidden' value='<?php echo htmlentities($vo['id'],ENT_QUOTES); ?>' name='id'><?php endif; ?><div class="layui-form-item text-center"><button class="layui-btn" type='submit'>保存数据</button><button class="layui-btn layui-btn-danger" type='button' data-confirm="确定要取消编辑吗？" data-close>取消编辑</button></div></form>