<?php /*a:1:{s:71:"/www/wwwroot/uexwash.com/ThinkAdmin/app/store/view/order/edit_take.html";i:1682158751;}*/ ?>
<form action="<?php echo sysuri(); ?>" method="post" data-auto="true" class="layui-form layui-card" data-table-id="BaseTable"><div class="layui-card-body padding-left-40"><div class="layui-form-item"><label class="layui-form-label"><?php echo htmlentities($title,ENT_QUOTES); ?></label><div class="layui-input-block"><select class="layui-select" lay-search name="processType" lay-filter="type"><?php foreach($texts as $key=>$value): if($processType == $key): ?><option selected value="<?php echo htmlentities($key,ENT_QUOTES); ?>"><?php echo htmlentities($value,ENT_QUOTES); ?></option><?php else: ?><option value="<?php echo htmlentities($key,ENT_QUOTES); ?>"><?php echo htmlentities($value,ENT_QUOTES); ?></option><?php endif; ?><?php endforeach; ?></select></div></div><div class="layui-form-item" ><label class="layui-form-label">地址</label><div class="layui-input-block"><input name="address" id="address"  value='<?php echo htmlentities((isset($storeAddr['address']) && ($storeAddr['address'] !== '')?$storeAddr['address']:""),ENT_QUOTES); ?>' required placeholder="请输入地址" class="layui-input"><p class="help-block"><b>必选</b>，请填写地址</p></div></div><div class="layui-form-item"  ><label class="layui-form-label">联系人</label><div class="layui-input-block"><input name="contacts" id="contacts" value='<?php echo htmlentities($storeAddr['name'],ENT_QUOTES); ?>(<?php echo htmlentities((isset($storeAddr['contacts']) && ($storeAddr['contacts'] !== '')?$storeAddr['contacts']:"无"),ENT_QUOTES); ?>)' required placeholder="请输入联系人" class="layui-input"><p class="help-block"><b>必选</b>，请填写联系人</p></div></div><div class="layui-form-item" ><label class="layui-form-label">电话</label><div class="layui-input-block"><input name="phone" id="phone" value='<?php echo htmlentities((isset($storeAddr['mobile']) && ($storeAddr['mobile'] !== '')?$storeAddr['mobile']:""),ENT_QUOTES); ?>' required placeholder="请输入联系电话" class="layui-input"><p class="help-block"><b>必选</b>，请填写电话</p></div></div><input type='hidden' value='<?php echo htmlentities($type,ENT_QUOTES); ?>' name='type'/><?php if(!(empty($order_id) || (($order_id instanceof \think\Collection || $order_id instanceof \think\Paginator ) && $order_id->isEmpty()))): ?><input type='hidden' value='<?php echo htmlentities($order_id,ENT_QUOTES); ?>' name='order_id'/><?php endif; ?></div><div class="hr-line-dashed"></div><div class="layui-form-item text-center"><button class="layui-btn" type='submit'>确定</button><button class="layui-btn layui-btn-danger" type='button'  data-close>取消</button></div><script>
        form.on('select(type)', function(data){
             var address = '<?php echo htmlentities((isset($storeAddr['address']) && ($storeAddr['address'] !== '')?$storeAddr['address']:""),ENT_QUOTES); ?>';
             var contacts = '<?php echo htmlentities($storeAddr['name'],ENT_QUOTES); ?>(<?php echo htmlentities((isset($storeAddr['contacts']) && ($storeAddr['contacts'] !== '')?$storeAddr['contacts']:"无"),ENT_QUOTES); ?>)';
             var phone = '<?php echo htmlentities((isset($storeAddr['mobile']) && ($storeAddr['mobile'] !== '')?$storeAddr['mobile']:""),ENT_QUOTES); ?>';
             if(data.value==2){
                  address = '<?php echo htmlentities((isset($orderAddr['address']) && ($orderAddr['address'] !== '')?$orderAddr['address']:""),ENT_QUOTES); ?>';
                  contacts = '<?php echo htmlentities((isset($orderAddr['name']) && ($orderAddr['name'] !== '')?$orderAddr['name']:""),ENT_QUOTES); ?>';
                  phone = '<?php echo htmlentities((isset($orderAddr['phone']) && ($orderAddr['phone'] !== '')?$orderAddr['phone']:""),ENT_QUOTES); ?>';
             }
             $("#address").val(address);
             $("#contacts").val(contacts);
             $("#phone").val(phone);
        }); 
    </script></form>